[package]
name = "transitland-atlas"
version = "0.1.0"
edition = "2021"

[dependencies]
dmfr = "0.2.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"

[[bin]]
name = "check"
path = "src/check/check.rs"
